// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhzvkkhbfgsslelkncwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoenZra2hiZmdzc2xlbGtuY3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODI4MTksImV4cCI6MjA2NjQ1ODgxOX0.vQdSgNm3L4C8g4tGzA_Y48TQeTjJf8-Pewvb01O6WG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);