// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnbgljiemqhyoqizmgoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuYmdsamllbXFoeW9xaXptZ296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjQ4NTcsImV4cCI6MjA2NTUwMDg1N30.Z0eZo2JKKSC54guUNG4q1tbHMvmWzbwCj8aLfvEq3eI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);